app = "tax-reminder-bot"
primary_region = "waw"

[env]
  TELEGRAM_TOKEN = ""
  TELEGRAM_CHAT_ID = ""

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0