app = "tax-reminder-bot"
primary_region = "ams"

[build]
dockerfile = "Dockerfile"

[env]
TELEGRAM_TOKEN = ""
TELEGRAM_CHAT_ID = ""

[[services]]
internal_port = 8080
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80