
app = "tax-reminder-bot"
primary_region = "waw"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  TELEGRAM_TOKEN = ""
  TELEGRAM_CHAT_ID = ""

[experimental]
  auto_rollback = true

[processes]
  app = "python bot_code.py"
