name: Deploy to Fly.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH=$PATH:$HOME/.fly/bin
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl launch --copy-config --auto-confirm --now --remote-only --name tax-reminder-bot
